# Generated by Django 4.1.5 on 2023-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_membership_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='bonus',
            field=models.TextField(),
        ),
    ]
